[tool.poetry]
name = "setup-python-example"
version = "0.1.0"
description = ""
authors = ["priya-kinthali <priya-kinthali@github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
