[server]
host = "localhost"        # TODO: helloooo     
port = 8080
ssl = false

[database]
url = "mongodb://localhost:27017" # TODO: helloooo
name = "mydb"
username = "myuser"
password = "mypassword"
level = "info"
