[tool.poetry]
name = "setup-python-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = {}

[tool.poetry.scripts]
example = "hello:main"