name: Test Python Tk
on:
  push:
    branches:
      - test-649
  workflow_dispatch:

jobs:
  tests-poetry:
    strategy:
      matrix:
        os: [macos-13, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Check tk.h version
        run: |
          echo "tk.h version:"
          grep "TCL_VERSION" /usr/include/tk.h || echo "tk.h not found"

      - name: Check libtk.a version
        run: |
          echo "libtk.a version:"
          nm /usr/lib/libtk.a | grep "Tcl_InitStubs" || echo "libtk.a not found"

