name: Test Python Tk
on:
  # push:
  #   branches:
  #     - test-649
  workflow_dispatch:

jobs:
  tests-poetry:
    strategy:
      matrix:
        os: [macos-13]
        python-version: ["3.10.11"]
      fail-fast: false
    name: ${{ matrix.python-version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Check all environment variables
        run: printenv
      - name: Prepare Ubuntu xvfb
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libxkbcommon-x11-0 xvfb
      - name: Prepare macOS Tk
        if: runner.os == 'macOS'
        run: |
          brew install tcl-tk
          echo 'export PATH="/usr/local/opt/tcl-tk/bin:$PATH"' >> $GITHUB_ENV
          echo 'export LDFLAGS="-L/usr/local/opt/tcl-tk/lib"' >> $GITHUB_ENV
          echo 'export CPPFLAGS="-I/usr/local/opt/tcl-tk/include"' >> $GITHUB_ENV
          echo 'export TCL_LIBRARY="/usr/local/opt/tcl-tk/lib"' >> $GITHUB_ENV
          echo 'export TK_LIBRARY="/usr/local/opt/tcl-tk/lib"' >> $GITHUB_ENV
      - name: Run tk script (closes itself after 5 seconds) - Ubuntu
        if: runner.os == 'Linux'
        run: xvfb-run python tk_min.py
      - name: Run tk script (closes itself after 5 seconds)
        if: runner.os != 'Linux'
        run: python tk_min.py