name: check latest

on:
  push:
    branches:
      - test-973
  workflow_dispatch:

jobs:

  test-with-t:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version:
          - '3.13.1t'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: priyagupta108/setup-python@test-pr-973
        with:
          python-version: ${{ matrix.python-version }}



