name: check latest

on:
  push:
    branches:
      - test-973
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest,ubuntu-22.04, ubuntu-20.04, windows-latest, windows-2019, macos-13, macos-latest]
        os: [ubuntu-latest]
        python-version: ['3.13t']

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # - name: Set up Python
      #   # uses: priyagupta108/setup-python@test-pr-973
      #   uses: actions/setup-python@main
      #   # uses: mahabaleshwars/setup-python@feature/tool-versions-file-support
      #   with:
      #     # python-version-file: '.tool-versions'
      #     python-version: 3.13.2t
      #     # freethreaded: true
      #     # check-latest: true
      # - name: Verify Python Version
      #   run: |
      #     python -VVV

      - name: Setup Python and check latest
        uses: actions/setup-python@main
        with:
          python-version: ${{ matrix.python-version }}
          # freethreaded: true
      # - name: Verify 3.12.7
      #   run: python __tests__/verify-python.py 3.13.1t
      # - name: Run python-path sample 3.13.2t
      #   run: pipx run --python '${{ steps.cp313.outputs.python-path }}' nox --version
      - name: Validate version
        run: |
          $pythonVersion = (python --version)
          Write-Host "Python version: $pythonVersion"
          echo "matrixversion is ${{ matrix.python-version }}"
          $matrixVersion = "${{ matrix.python-version }}"
          $matrixVersion = $matrixVersion -replace 't', ''
          if ($pythonVersion -NotMatch $matrixVersion){
            Write-Host "The current version is $pythonVersion; expected version is $matrixVersion"
            exit 1
          }
          $pythonVersion
          # if ("$pythonVersion" -NotMatch "${{ matrix.python-version -replace 't', '' }}"){
          #   Write-Host "The current version is $pythonVersion; expected version is ${{ matrix.python-version }}"
          #   exit 1
          # }
          # $pythonVersion
        shell: pwsh




