name: Test Python Setup

on:
  push:
    branches:
      - test-871-portablebinary

jobs:
  test-python-setup:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure Sudo is Installed
        run: |
          if ! command -v sudo &> /dev/null; then
            echo "sudo could not be found. Installing..."
            sudo apt-get update && sudo apt-get install -y sudo
          fi

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Create Python temp_script.sh
        run: |
          PYTHON_PATH=$(which python3)
          PYTHON_DIR=$(dirname $PYTHON_PATH)
          sudo bash -c "export LD_LIBRARY_PATH=$PYTHON_DIR/../lib; export PATH=$PYTHON_DIR:\$PATH; python --version"

      #     echo "export LD_LIBRARY_PATH=$PYTHON_DIR/../lib" >> temp_script.sh
      #     echo "export PATH=$PYTHON_DIR:\$PATH" >> temp_script.sh
      #     echo "python --version" >> temp_script.sh
      #     chmod +x temp_script.sh

      # - name: Check Python Version with Sudo
      #   run: sudo ./temp_script.sh

      - name: Print RUNNER_TOOL_CACHE
        run: echo "RUNNER_TOOL_CACHE is $RUNNER_TOOL_CACHE"

      - name: Print AGENT_TOOLSDIRECTORY
        run: echo "AGENT_TOOLSDIRECTORY is $AGENT_TOOLSDIRECTORY"

      - name: Check Python version
        run: python --version

      # - name: Set Environment Variables and Check Python Version with Sudo
      #   run: |
      #     PYTHON_PATH=$(which python3)
      #     PYTHON_DIR=$(dirname $PYTHON_PATH)
      #     export LD_LIBRARY_PATH=$PYTHON_DIR/../lib
      #     export PATH=$PYTHON_DIR:$PATH
      #     sudo env "LD_LIBRARY_PATH=$LD_LIBRARY_PATH" "PATH=$PATH" python --version

      # - name: Print Python path
      #   run: which python
      # - name: Check Python version
      #   run: |
      #       ldd $(which python)
      #       sudo ${{ env.pythonLocation }}/bin/python --version
      
      # - name: Set LD_LIBRARY_PATH and check python version
      #   run: |
      #     export LD_LIBRARY_PATH=$(dirname $(which python))/../lib
      #     python --version
      #------------------------
      # - name: Create Python Wrapper Script
      #   run: |
      #     PYTHON_PATH=$(which python3)
      #     PYTHON_DIR=$(dirname $PYTHON_PATH)
      #     echo '#!/bin/bash' > python_wrapper.sh
      #     echo "export LD_LIBRARY_PATH=$PYTHON_DIR/../lib" >> python_wrapper.sh
      #     echo "$PYTHON_PATH \"\$@\"" >> python_wrapper.sh
      #     chmod +x python_wrapper.sh

      # - name: Check Python Version with Sudo
      #   run: sudo ./python_wrapper.sh --version

      # ------------------------------
      # - name: Create Python temp_script.sh
      #   run: |
      #     PYTHON_PATH=$(which python3)
      #     PYTHON_DIR=$(dirname $PYTHON_PATH)
      #     echo "export LD_LIBRARY_PATH=$PYTHON_DIR/../lib" >> temp_script.sh
      #     echo "export PATH=$PYTHON_DIR:\$PATH" >> temp_script.sh
      #     echo "python --version" >> temp_script.sh
      #     chmod +x temp_script.sh

      # - name: Check Python Version with Sudo
      #   run: sudo ./temp_script.sh