name: Setuptools Python application test with GitHub Actions

on:
  push:
    branches: [ 872-test-setuptools ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11.5
      uses: actions/setup-python@v5
      with:
        python-version: 3.11.5

    - name: Set up virtual environment
      run: |
        python -m venv env
        source env/bin/activate
    - name: Install Dependencies
      run: |
        python -m pip install setuptools==69.5.1
        python -m pip install django-allauth==0.44.0


       
    - name: Check setuptools version
      run: pip show setuptools

   