name: Test Python Setup

on:
  push:
    branches:
      - test-871-portablebinary

jobs:
  test-python-setup:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Print RUNNER_TOOL_CACHE
        run: echo "RUNNER_TOOL_CACHE is $RUNNER_TOOL_CACHE"

      - name: Print AGENT_TOOLSDIRECTORY
        run: echo "AGENT_TOOLSDIRECTORY is $AGENT_TOOLSDIRECTORY"

      - name: Print Python path
        run: which python
      - name: Set LD_LIBRARY_PATH and check python version
        run: |
          export LD_LIBRARY_PATH=$(dirname $(which python))/../lib
          python --version