name: Test Python Setup

on:
  push:
    branches:
      - test-871-portablebinary

jobs:
  test-python-setup:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
     
      - name: Unset LD_LIBRARY_PATH and check Python version without sudo
        run: |
          unset LD_LIBRARY_PATH
          LD_PRELOAD=/home/azureuser/actions-runner/_work/_tool/Python/3.12.4/x64/lib 
          python --version
      # - name: Unset LD_LIBRARY_PATH and check Python version without sudo
      #   run: |
      #     unset LD_LIBRARY_PATH
      #     python --version
      # - name: Check Python version with sudo
      #   run: |
      #     sudo python --version
         
      - name: Check Python version
        run: python --version
   
   