name: test Python 3.13 fails to install on windows

on:
  push:
    branches: [ test-888-artifacts ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
        allow-prereleases: true
        cache: pip
   

    - name: Check Python version
      run: python --version
    - name: Install Dependencies
      run: |
        
          python -m pip install wheel

       
   
   