name: Test Python Setup

on:
  push:
    branches:
      - test-871-portablebinary

jobs:
  test-python-setup:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure Sudo is Installed
        run: |
          if ! command -v sudo &> /dev/null; then
            echo "sudo could not be found. Installing..."
            sudo apt-get update && sudo apt-get install -y sudo
          fi
      # - name: Set AGENT_TOOLSDIRECTORY
      #   run: |
      #     # Create the directory
      #     sudo mkdir -p /opt/hostedtoolcache/Python
      #     # Change ownership of the directory to the current user and group
      #     sudo chown -R $(whoami):$(id -gn) /opt/hostedtoolcache
      #     # Export the environment variable
      #     echo "AGENT_TOOLSDIRECTORY=/opt/hostedtoolcache/Python" >> $GITHUB_ENV
      #     # Verify Python version
      #     sudo bash -c "export LD_LIBRARY_PATH=$PYTHON_DIR/lib:\$LD_LIBRARY_PATH && $PYTHON_DIR/bin/python --version"
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
        env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache
 
      # - name: Print tool directory path
      #   run: echo $RUNNER_TOOL_CACHE

      - name: Print temp directory path
        run: echo $RUNNER_TEMP

      
      # - name: Preserve LD_LIBRARY_PATH for Sudo
      #   run: |
      #     echo 'Defaults env_keep += "LD_LIBRARY_PATH"' | sudo tee /etc/sudoers.d/env_keep

      # - name: Verify Python Installation
      #   run: |
      #     sudo env "PATH=$PATH" python --version
         

      # - uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.9'
      # - name: Create Python temp_script.sh
      #   run: |
      #     PYTHON_PATH=$(which python3)
      #     PYTHON_DIR=$(dirname $PYTHON_PATH)
      #     sudo bash -c "export LD_LIBRARY_PATH=$PYTHON_DIR/../lib; export PATH=$PYTHON_DIR:\$PATH; python --version"
#--------------------------
      #     echo "export LD_LIBRARY_PATH=$PYTHON_DIR/../lib" >> temp_script.sh
      #     echo "export PATH=$PYTHON_DIR:\$PATH" >> temp_script.sh
      #     echo "python --version" >> temp_script.sh
      #     chmod +x temp_script.sh

      # - name: Check Python Version with Sudo
      #   run: sudo ./temp_script.sh

      - name: Print RUNNER_TOOL_CACHE
        run: echo "RUNNER_TOOL_CACHE is $RUNNER_TOOL_CACHE"

      - name: Print AGENT_TOOLSDIRECTORY
        run: |
          echo "AGENT_TOOLSDIRECTORY is $AGENT_TOOLSDIRECTORY"
        env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache

      - name: Add Python Path to Sudo Environment
        run: |
          PYTHON_PATH=$(dirname $(which python))
          echo "Defaults secure_path=\"$PYTHON_PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin\""

      # echo "Defaults secure_path=\"$PYTHON_PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\"" | sudo tee /etc/sudoers.d/python-path

      - name: Verify Python Installation
        run: |
          sudo python --version
          python --version
      # - name: Check Python version
      #   run: python --version

      # - name: Set Environment Variables and Check Python Version with Sudo
      #   run: |
      #     PYTHON_PATH=$(which python3)
      #     PYTHON_DIR=$(dirname $PYTHON_PATH)
      #     export LD_LIBRARY_PATH=$PYTHON_DIR/../lib
      #     export PATH=$PYTHON_DIR:$PATH
      #     sudo env "LD_LIBRARY_PATH=$LD_LIBRARY_PATH" "PATH=$PATH" python --version

      # - name: Print Python path
      #   run: which python
      # - name: Check Python version
      #   run: |
      #       ldd $(which python)
      #       sudo ${{ env.pythonLocation }}/bin/python --version
      
      # - name: Set LD_LIBRARY_PATH and check python version
      #   run: |
      #     export LD_LIBRARY_PATH=$(dirname $(which python))/../lib
      #     python --version
      #------------------------
      # - name: Create Python Wrapper Script
      #   run: |
      #     PYTHON_PATH=$(which python3)
      #     PYTHON_DIR=$(dirname $PYTHON_PATH)
      #     echo '#!/bin/bash' > python_wrapper.sh
      #     echo "export LD_LIBRARY_PATH=$PYTHON_DIR/../lib" >> python_wrapper.sh
      #     echo "$PYTHON_PATH \"\$@\"" >> python_wrapper.sh
      #     chmod +x python_wrapper.sh

      # - name: Check Python Version with Sudo
      #   run: sudo ./python_wrapper.sh --version

      # ------------------------------

      #------------

      # - name: Create Python temp_script.sh
      #   run: |
      #     PYTHON_PATH=$(which python3)
      #     PYTHON_DIR=$(dirname $PYTHON_PATH)
      #     echo "export LD_LIBRARY_PATH=$PYTHON_DIR/../lib" >> temp_script.sh
      #     echo "export PATH=$PYTHON_DIR:\$PATH" >> temp_script.sh
      #     echo "python --version" >> temp_script.sh
      #     chmod +x temp_script.sh

      # - name: Check Python Version with Sudo
      #   run: sudo ./temp_script.sh
      