name: Test Python Setup

on:
  push:
    branches:
      - test-897-parse-version

jobs:
  test-python-setup:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macOS-13]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python from pyproject.toml
       
        # uses: priya-kinthali/setup-python@fix-935-tomlparse
        uses: actions/setup-python@v5.1.1

        

        with:
          python-version-file: pyproject.toml   
         
      - name: Check Python version
        run: python --version
   
   