name: Test Python Setup with pyproject.toml

on:
  push:
    branches:
      - test-pyprojtoml

jobs:
  test-python-setup:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macOS-13]
        # os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python from pyproject.toml
        uses: actions/setup-python@v5
        # uses: priya-kinthali/setup-python@fix-935-tomlparse
        with:
          python-version-file: pyproject.toml   
         
      - name: Check Python version
        run: python --version

   
   