name: test
on:
  push:
    branches:
      - test-649
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        id: python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8.15"
      - name: Set up environment for macOS
        if: runner.os == 'macOS'
        run: |
          brew reinstall tcl-tk
          echo 'export PATH="/usr/local/opt/tcl-tk/bin:$PATH"' >> $GITHUB_ENV
          echo 'export LDFLAGS="-L/usr/local/opt/tcl-tk/lib"' >> $GITHUB_ENV
          echo 'export CPPFLAGS="-I/usr/local/opt/tcl-tk/include"' >> $GITHUB_ENV
          echo 'export PKG_CONFIG_PATH="/usr/local/opt/tcl-tk/lib/pkgconfig"' >> $GITHUB_ENV
      - name: Prepare Ubuntu xvfb
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libxkbcommon-x11-0 xvfb
      - name: Run tk script (closes itself after 5 seconds) - Ubuntu
        if: runner.os == 'Linux'
        run: xvfb-run python tk_min.py
      - name: Run tk script (closes itself after 5 seconds)
        if: runner.os != 'Linux'
        run: python tk_min.py
        env:
          PATH: "/usr/local/opt/tcl-tk/bin:$PATH"
          LDFLAGS: "-L/usr/local/opt/tcl-tk/lib"
          CPPFLAGS: "-I/usr/local/opt/tcl-tk/include"
          PKG_CONFIG_PATH: "/usr/local/opt/tcl-tk/lib/pkgconfig"
      