name: Python 3.5 Setup Test

on:
  push:
    branches: [ 866-test3.5 ]
 

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
          os: [ubuntu-20.04, macos-12]


    # runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4

    # - name: Install missing library
    #   run: |
    #     arch -arm64 brew install gettext
    #     ln -s /usr/local/opt/gettext/lib/libintl.8.dylib /usr/local/lib/

    - name: Set up Python 3.5
      # uses: priya-kinthali/setup-python@868-test-urllib3
      uses: actions/setup-python@v5
      with:
        python-version: 3.5
      # env:
      #   PIP_TRUSTED_HOST: "pypi.python.org pypi.org files.pythonhosted.org"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt