name: Python workflow

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: priya-kinthali/setup-python@708-pr-test-agent
        with:
          python-version: '3.11.6'
      - name: Check Python version
        run: python --version