name: Python application
on: 
  push:
  schedule:
    # Run workflow every 5 minutes
    - cron:  '*/5 * * * *'
jobs:
  build:
    runs-on:  [self-hosted, macos] 
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"