name: Test pip cache

on:
  push:
    branches:
      - test-973
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest,ubuntu-22.04, ubuntu-20.04, windows-latest, windows-2019, macos-13, macos-latest]
        python-version: ['3.13.1t', '3.13.1', '3.12.9']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: priyagupta108/setup-python@test-pr-973
        # uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          # freethreaded: true
          cache: 'pip'
      - run: pip install -r requirements.txt



