name: Test Multiple Python Versions (3.13t -> 3.13)

on:
  push:
    branches:
      - test-973
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 1
        uses: Quansight-Labs/setup-python@v5
        with:
          python-version: "3.13t"

      - name: Display Python version 1
        run: python -c "import sys; print(sys.version)"

      - run: python -VVV

      - run: |
          python -m pip install numpy
          python -c "import numpy; print(numpy.random.randn(10))"
      - name: Set up Python 2
        uses: Quansight-Labs/setup-python@v5
        with:
          python-version: "3.13"

      - name: Display Python version 2
        run: python -c "import sys; print(sys.version)"

      - run: python -VVV

      - run: |
          python -m pip install numpy
          python -c "import numpy; print(numpy.random.randn(10))"
