name: Build and Test
on:
  push:
    branches:
      - test-649
  workflow_dispatch:

jobs:
  verify-tkinter:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-13, ubuntu-22.04, ubuntu-20.04]
        python-version: ["3.10.1", '3.10.4']
      fail-fast: false


    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Verify Tcl/Tk version
      run: |
        python -c "import tkinter; print(tkinter.TkVersion)"