name: Python workflow

on:
  push:
    branches: [ poc-756-rawapi ]
  workflow_dispatch:
  

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11.6
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.6'

    - name: Display Python version
      run: python --version