name: Setup Python on Windows Server 2022

on:
  push:
    branches:
      - test-769
  workflow_dispatch:
    

jobs:
  test-python:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.8.10
        uses: priya-kinthali/setup-python@test-930
        with:
          python-version: 3.8.10
          cache: 'pip'
         

      - name: Display Python version
        run: python --version

      - name: Install dependencies
        run: pip install -r requirements.txt