name: Test Python Setup

on: 
  push:
    branches:
      - test-769
  workflow_dispatch:

jobs:
  test-python-setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13.0-alpha - 3.13.0'
      - name: Verify Python Version
        run: python --version