name: SandBox ubuntu

on:
  # push:
  workflow_dispatch:

jobs:
  setup_python:
    name: ${{ matrix.os }} ${{ matrix.architecture }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: ["windows-latest", "ubuntu-latest", "macos-13"]
        os: [ "ubuntu-latest"]

        # architecture: ["x64"]
        # include:
        #   - os: "windows-latest"
        #     architecture: "x86"
        #   - os: "macos-14"
        #     architecture: "arm64"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: priya-kinthali/setup-python@freethread-pr-319
        with:
          python-version: "3.13.0t"
          # architecture: "x64-freethreaded"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.0"
          # architecture: "x64"
      - name: Check python
        run: |
          set -ex
          echo "$PATH"
          if [ -d /c/hostedtoolcache/windows ]; then
              find /c/hostedtoolcache/windows/Python/3.13.0 -maxdepth 2 -name 'python*'
              py --list
          fi
          which python
          which python3
          which python3.13.0 || true
          which python3.13.0t
          python3.13.0 -VV || python3 -VV
          python3.13.0t -VV
        shell: bash
