name: SandBox win,darwin

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest,ubuntu-22.04, ubuntu-20.04, windows-latest, windows-2019, macos-13, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: priyagupta108/setup-python@test-pr-973
        with:
          python-version: "3.13.1t"
          # architecture: ${{ matrix.architecture }}
          cache: 'pip'
      - name: Set up Python
        uses: priyagupta108/setup-python@test-pr-973
        with:
          python-version: "3.13.1"
          # architecture: ${{ matrix.architecture }}
          cache: 'pip'
      - name: Check python
        run: |
          set -ex
          echo "$PATH"
          # if [ -d /c/hostedtoolcache/windows ]; then
          #     find /c/hostedtoolcache/windows/Python/3.13.0 -maxdepth 2 -name 'python*'
          #     py --list
          # fi
          which python
          which python3
          which python3.13 || true
          which python3.13t
          python3.13 -VV || python3 -VV
          python3.13t -VV
        shell: bash
