name: Test pipenv
on:
  push:
    branches:
      - test-973
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest,ubuntu-22.04, ubuntu-20.04, windows-latest, windows-2019, macos-13, macos-latest]
        # python-version: ['3.13.1t', '3.13.1', '3.12', '3.11', '3.10']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        # uses: actions/setup-python@v5
        # uses: priyagupta108/setup-python@test-pr-973
        # with:
        #   python-version: ${{ matrix.python-version }}
          # freethreaded: true
        uses: mahabaleshwars/setup-python@feature/tool-versions-file-support
        with:
          python-version-file: '.tool-versions'
          cache: 'pipenv'
      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      - run: pipenv install --python ${{ matrix.python-version }}


