name: Test Multiple Python Versions (3.13t -> 3.13)

on:
  # push:
  #   branches:
  #     - test-973
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]
    steps:
      - uses: actions/checkout@v4
      - name: Clear existing Python versions
        run: |
          sudo rm -rf /Users/runner/hostedtoolcache/Python

      - name: Set up Python
        uses: quansight-labs/setup-python@v5
        with:
          python-version: "3.13t"
          architecture: ${{ matrix.architecture }}
      - name: Set up Python
        uses: quansight-labs/setup-python@v5
        with:
          python-version: "3.13"
          architecture: ${{ matrix.architecture }}
      - name: Check python
        run: |
          set -ex
          echo "$PATH"
          if [ -d /c/hostedtoolcache/windows ]; then
              find /c/hostedtoolcache/windows/Python/3.13.0 -maxdepth 2 -name 'python*'
              py --list
          fi
          which python
          which python3
          which python3.13 || true
          which python3.13t
          python3.13 -VV || python3 -VV
          python3.13t -VV
        shell: bash

