name: Test pipenv
on:
  push:
    branches:
      - test-973
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest,ubuntu-22.04, ubuntu-20.04, windows-latest, windows-2019, macos-13, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        # uses: mahabaleshwars/setup-python@feature/tool-versions-file-support
        # uses: actions/setup-python@v5
        uses: actions/setup-node@v4

        with:
          # python-version-file: '.tool-versions' # Read python version from a file pyproject.toml, .python-version nodejs 20 #comment1
          node-version-file: '.tool-versions' # Read node version from a file  nodejs 22 #comment1
          # freethreaded: true
      # - name: Verify Python Version
      #   run: |
      #     python -VVV
      - name: Verify Node.js Version
        run: |
          node -v


