name: Test with hardcoded AGENT_TOOLSDIRECTORY on macOS
on: 
  push:
    branches:
      - test-708
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, macos-latest, macos-13, self-hosted]
        python-version: ['3.10', '3.12']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install OpenSSL
        run: brew install openssl@3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Configure OpenSSL for Python
        run: |
          export LDFLAGS="-L/usr/local/opt/openssl@3/lib"
          export CPPFLAGS="-I/usr/local/opt/openssl@3/include"
          export PATH="/usr/local/opt/openssl@3/bin:$PATH"
          echo 'export LDFLAGS="-L/usr/local/opt/openssl@3/lib"' >> ~/.zshrc
          echo 'export CPPFLAGS="-I/usr/local/opt/openssl@3/include"' >> ~/.zshrc
          echo 'export PATH="/usr/local/opt/openssl@3/bin:$PATH"' >> ~/.zshrc
          source ~/.zshrc
          python3 -m ensurepip --upgrade
      - name: Check Python version
        run: python --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      
