name: Reproduce Issue

on:
  push:
    branches:
      - test-769
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'

    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install requests

    - name: Run a script
      run: |
        echo "Running some script"