name: Python 3.5 Setup Test

on:
  push:
    branches: [ 866-test3.5 ]
 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.5
      uses: actions/setup-python@v5
      with:
        python-version: 3.5

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt