name: Python arm64 workflow

on: [push]

jobs:
  build:
    runs-on: self-hosted # change this to your self-hosted runner label

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Display Python version
      run: python --version