# name: Python
# on: [workflow_dispatch]

# jobs:
#   build:
#     strategy:
#       fail-fast: false
#       matrix:
#         target:
#           - os: "windows-latest"
#             architecture: "x64"
#           - os: "windows-latest"
#             architecture: "x86"
#     defaults:
#       run:
#         shell: bash
#     runs-on: ${{ matrix.target.os }}
    

#     steps:
#       - uses: actions/checkout@v4
#       - name: Install poetry
#         run: pipx install poetry
#       - name: Setup Python
#         uses: actions/setup-python@v5
#         id: setup-python
#         with:
#           python-version: "3.11"
#           architecture: ${{ matrix.target.architecture }}
#           cache: "poetry"

name: test cachekey conflict with workaround for 826
on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - os: "windows-latest"
            architecture: "x64"
          - os: "windows-latest"
            architecture: "x86"
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.target.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: "3.11"
          architecture: ${{ matrix.target.architecture }}
          cache: 'none'
          cache-dependency-path: '**/poetry.lock'
          # cache-prefix: "${{ runner.os }}-python-3.11-${{ matrix.target.architecture }}-poetry"
      - name: Cache poetry
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ steps.setup-python.outputs.python-version }}-${{ matrix.target.architecture }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-${{ steps.setup-python.outputs.python-version }}-${{ matrix.target.architecture }}-
            ${{ runner.os }}-poetry-${{ steps.setup-python.outputs.python-version }}-
            ${{ runner.os }}-poetry-
            ${{ runner.os }}-

