name: Setup Python on Windows Server 2022

on:
  push:
    branches:
      - test-769
  workflow_dispatch:

jobs:
  setup-python-multiple-python-versions:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-22.04
          - ubuntu-latest
          - windows-latest
          - macos-latest
          - macos-13

    steps:
      - uses: actions/checkout@v4

      - name: Run with setup-python 3.8
        if: matrix.os != 'macos-latest' && matrix.os != 'windows-latest'
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Verify 3.8
        run: python __tests__/verify-python.py 3.8

  
# [tool.poetry]
# name = "sample-python"
# version = "0.1.0"
# description = "test"
# authors = ["Your Name <you@example.com>"]
# readme = "README.md"

# [tool.poetry.dependencies]
# python = "^3.8"


# [build-system]
# requires = ["poetry-core"]
# build-backend = "poetry.core.masonry.api"
