name: Path update for >=3.10
on:
  push:
    branches:
      - test-973
  workflow_dispatch:

jobs:
  install_and_check:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11']
        architecture: ['x86', 'x64']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: aparnajyothi-y/setup-python@update-install-path
        # uses: actions/setup-python@v5

        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      
      - name: Install pyinstaller with --user flag
        run: |
          pip install pyinstaller --user
        
      - name: Verify installation
        run: |
          pyinstaller --version
          echo $Env:PATH