name: Setup Python on Windows Server 2022

on:
  push:
    branches:
      - test-769
  workflow_dispatch:

jobs:
    test-setup-python-older:
      name: Test setup-python 3.8
      runs-on: ${{ matrix.operating-system }}
      strategy:
        matrix:
          os:
            [
              ubuntu-20.04,
              ubuntu-22.04,
              ubuntu-latest,
              windows-latest,
              macos-latest,
              macos-13
            ]
          python: [3.8.10, 3.8.18]
          exclude:
            - os: ubuntu-22.04
              python: '3.8.10'
            - os: ubuntu-latest
              python: '3.8.10'
            - os: macos-latest
              python: '3.8.18'
            - os: windows-latest
              python: '3.8.18'
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Run with setup-python ${{ matrix.python }}
          id: setup-python
          uses: ./
          with:
            python-version: ${{ matrix.python }}
        - name: Verify ${{ matrix.python }}
          run: python __tests__/verify-python.py ${{ matrix.python }}
  
# [tool.poetry]
# name = "sample-python"
# version = "0.1.0"
# description = "test"
# authors = ["Your Name <you@example.com>"]
# readme = "README.md"

# [tool.poetry.dependencies]
# python = "^3.8"


# [build-system]
# requires = ["poetry-core"]
# build-backend = "poetry.core.masonry.api"
