name: Outputs

on:
  push:
    branches:
      - test-973
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest,ubuntu-22.04, ubuntu-20.04, windows-latest, windows-2019, macos-13, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: priyagupta108/setup-python@test-pr-973
        id: cp312
        with:
          python-version: "3.13.1"
          freethreaded: true
          cache: "poetry"
      - run: echo '${{ steps.cp312.outputs.cache-hit }}' # true if cache-hit occurred on the primary key
      # - run: echo '${{ steps.cp312.outputs.python-version }}'
      # - run: pipx run --python '${{ steps.cp312.outputs.python-path }}' nox --version
      - name: Verify Python Version
        run: |
          python -VVV
          



