name: Test PR for Free Threaded Python Versions

on:
  push:
    branches:
      - test-973
  workflow_dispatch:

jobs:
  tests-freethreaded:
    strategy:
      matrix:
        # os: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04, macos-13-xlarge, macos-14, macos-15, macos-13, macos-latest-large, macos-15-large, windows-latest, windows-2019, windows-2022]  
        # os: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04, macos-14, macos-13, windows-2019]  
        os: [windows-2019]  
        # python-version: ["3.10.10t", "3.12.3t", "3.12.7t", "3.13.0t"]
        python-version: [3.13t]

      fail-fast: false
    name: ${{ matrix.python-version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      # - name: Set up Python ${{ matrix.python-version }}
      #   # uses: actions/setup-python@v5
      #   # uses: priya-kinthali/setup-python@freethread-pr-319
      #   uses: priyagupta108/setup-python@test-pr-973
      #   with:
      #     python-version: ${{ matrix.python-version }}
          # architecture: 'x64-freethreaded'
      - name: Manually install freethreaded Python on Windows
        if: matrix.os == 'windows-2019'
        run: |
          $pythonVersion = '${{ matrix.python-version }}'
          if ($pythonVersion -eq '3.13t') {
            $pythonVersion = '3.13.1'  # Adjust this to the specific version you need
          }
          $url = "https://www.python.org/ftp/python/$pythonVersion/python-$pythonVersion-amd64.exe"
          Invoke-WebRequest -Uri $url -OutFile "python-$pythonVersion-amd64.exe"
          Start-Process -FilePath "python-$pythonVersion-amd64.exe" -ArgumentList "/quiet Include_freethreaded=1" -Wait
          Remove-Item -Force "python-$pythonVersion-amd64.exe"
          $freethreadedPath = [System.IO.Path]::Combine($env:LOCALAPPDATA, 'Programs', 'Python', 'Python313', 'python3.13t.exe')
          echo $freethreadedPath >> $Env:GITHUB_PATH
      - name: Verify Python Version
        run: |
          python -c "import sys; print(sys.version)"
      - name: Run thread.py
        run: |
          python thread.py







    
