name: Setup Python with Version File

on: 
  workflow_dispatch:
  push:
     branches: [ "main" ]
  pull_request:
     branches: [ "main" ]

jobs:
  setup-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # - name: Set up Python
    #   uses: actions/setup-python@v5
    #   with:
    #     python-version-file: '.python-version'

    - name: Set up Python
      uses: lmvysakh/setup-python@test_787_all
      with:
        python-version-file: '.python-version'

    - name: Display Python version
      run: python --version