name: Setup Python on Windows Server 2022

on:
  push:
    branches:
      - test-983
  workflow_dispatch:
    

jobs:
  test-python:
    runs-on: macos-13
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.8.10
        uses: actions/setup-python@v5
        with:
          python-version: 3.8.10
          cache: 'pip'
         

      - name: Display Python version
        run: python --version

      - name: Install dependencies
        run: pip install -r requirements.txt