name: Checkout and Setup of Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: [macOS]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        # uses: priya-kinthali/setup-python@708-pr-test-agent
        uses: actions/setup-python@v5

        with:
          python-version: '3.11.6'
      - name: Check Python version
        run: python --version
