name: Test Python Setup

on:
  push:
    branches:
      - test-871-portablebinary

jobs:
  test-python-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Ensure Sudo is Installed
        run: |
          if ! command -v sudo &> /dev/null; then
            echo "sudo could not be found. Installing..."
            sudo apt-get update && sudo apt-get install -y sudo
          fi
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Add Python Path to Sudo Environment
        run: |
          PYTHON_PATH=$(dirname $(which python))
          echo "Defaults secure_path=\"$PYTHON_PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\"" | sudo tee /etc/sudoers.d/python-path

      - name: Verify Python Installation
        run: |
          sudo python --version
          python --version
