name: test Python 3.13 fails to install on windows

on:
  push:
    branches: [ test-888-artifacts ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: "3.8"
        allow-prereleases: true
        cache: pip
   

    - name: Check Python version
      run: python --version
   
       
   
   