name: Build and Test
on:
  push:
    branches:
      - test-649
  workflow_dispatch:

jobs:
  verify-tkinter:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-13, ubuntu-22.04, ubuntu-20.04]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Verify Tcl/Tk version
      run: |
        python -c "import tkinter; print(tkinter.TkVersion)"