name: test
on:
  # push:
  #   branches:
  #     - test-967
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python 3.12 on Ubuntu
        run: |
          sudo apt-get update
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt-get update
          sudo apt-get install -y python3.12 python3.12-venv python3.12-dev
          python3.12 --version
      - name: Get Python version
        run: python3.12 --version
      - name: Get pipx version
        run: pipx --version
      - name: Install Python Package
        run: pipx install .