name: Workflow 1 for actions/cache

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: 3.11
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ runner.architecture }}-${{ matrix.os }}-python-${{ matrix.python-version }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.architecture }}-${{ matrix.os }}-python-${{ matrix.python-version }}-pip-
    
      - name: Install dependencies
        run: pip install -r requirements.txt