name: Workflow 2

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: pip
          cache-dependency-path: setup.py
      - name: Check cache hash keys
        run: |
          echo 'Expected "Set up Python" hash: '"${{ hashFiles('setup.py') }}"
          echo '"Set up Python" should NOT use .github/workflows/test-742.yml hash: '"${{ hashFiles('.github/workflows/test-742.yml') }}"
      - name: Install dependencies
        run: pip install -r requirements.txt