name: Workflow 1

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: 3.11
          cache: pip
          cache-dependency-path: .github/workflows/workflow1.yml
      - name: Check cache hash keys
        run: |
          echo 'Expected "Set up Python" hash: '"${{ hashFiles('.github/workflows/workflow1.yml') }}"
          echo '"Set up Python" should NOT use setup.py hash: '"${{ hashFiles('setup.py') }}"
      - name: Install dependencies
        run: pip install -r requirements.txt
        # test2
